/**
 * Mock data used when no Firebase project is configured.
 * Mirrors realistic MAUDE statistics for UI development.
 */
import type { Manufacturer, Device } from './types'

// ── generate a rolling 12-month events map ────────────────────────────────────
function months12(base: number, variance = 0.3): Record<string, number> {
  const result: Record<string, number> = {}
  const now = new Date(2025, 11, 1) // Dec 2025
  for (let i = 11; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1)
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
    result[key] = Math.round(base * (1 + (Math.random() - 0.5) * variance))
  }
  return result
}

export const MOCK_MANUFACTURERS: Manufacturer[] = [
  {
    id: 'medtronic',
    name: 'Medtronic, Inc.',
    country: 'USA',
    total_events: 124_803,
    death_count: 2_341,
    injury_count: 54_209,
    malfunction_count: 68_253,
    recall_count: 47,
    recall_rate: 0.38,
    severity_score: 74,
    events_by_month: months12(10_400),
    top_devices: [
      { id: 'insulin-pump-670g', name: 'MiniMed 670G Insulin Pump', count: 31_200 },
      { id: 'crt-d-cardiac', name: 'Cardiac Resynchronization Device', count: 18_900 },
      { id: 'spinal-cord-stim', name: 'Spinal Cord Stimulator', count: 12_100 },
    ],
    device_classes: { 'Class I': 4_200, 'Class II': 62_000, 'Class III': 58_603 },
    last_updated: null,
    supply_chain_risk_score: 7.2,
    supply_chain_summary:
      'Medtronic relies on a global manufacturing network spanning Ireland, Puerto Rico, and China. Recent semiconductor shortages and single-source component dependencies elevate supply chain risk. Active mitigation programs are in place but lead-time volatility remains elevated.',
    countries: ['USA', 'Ireland', 'China', 'Puerto Rico', 'Costa Rica'],
    risk_tier: 'HIGH',
    recall_risk_score: 0.74,
    specialties: [],
    projected_event_rate_trend: 'INCREASING',
  },
  {
    id: 'abbott',
    name: 'Abbott Laboratories',
    country: 'USA',
    total_events: 98_441,
    death_count: 1_102,
    injury_count: 39_870,
    malfunction_count: 57_469,
    recall_count: 31,
    recall_rate: 0.31,
    severity_score: 61,
    events_by_month: months12(8_200),
    top_devices: [
      { id: 'freestyle-libre', name: 'FreeStyle Libre CGM', count: 42_100 },
      { id: 'heartmate-3', name: 'HeartMate 3 LVAD', count: 9_800 },
    ],
    device_classes: { 'Class I': 2_100, 'Class II': 55_000, 'Class III': 41_341 },
    last_updated: null,
    supply_chain_risk_score: 4.8,
    supply_chain_summary:
      'Abbott maintains a diversified supplier base across North America and Europe with redundant sourcing for critical sensor components. Strong inventory buffers and regional manufacturing hubs contribute to moderate risk resilience.',
    countries: ['USA', 'Germany', 'Netherlands', 'Mexico'],
    risk_tier: 'MEDIUM',
    recall_risk_score: 0.52,
    specialties: [],
    projected_event_rate_trend: 'STABLE',
  },
  {
    id: 'boston-scientific',
    name: 'Boston Scientific Corporation',
    country: 'USA',
    total_events: 87_654,
    death_count: 1_876,
    injury_count: 37_210,
    malfunction_count: 48_568,
    recall_count: 28,
    recall_rate: 0.32,
    severity_score: 68,
    events_by_month: months12(7_300),
    top_devices: [
      { id: 'watchman-flx', name: 'WATCHMAN FLX Device', count: 18_200 },
      { id: 'resonate-icd', name: 'RESONATE ICD', count: 14_500 },
    ],
    device_classes: { 'Class I': 1_800, 'Class II': 41_000, 'Class III': 44_854 },
    last_updated: null,
    supply_chain_risk_score: 6.1,
    supply_chain_summary:
      'Boston Scientific sources specialized cardiac and vascular components from Asia-Pacific suppliers with limited domestic alternatives. Geopolitical tensions and port congestion have caused periodic disruptions. Dual-sourcing efforts are ongoing.',
    countries: ['USA', 'Ireland', 'Malaysia', 'Japan', 'Costa Rica'],
    risk_tier: 'HIGH',
    recall_risk_score: 0.65,
    specialties: [],
    projected_event_rate_trend: 'STABLE',
  },
  {
    id: 'stryker',
    name: 'Stryker Corporation',
    country: 'USA',
    total_events: 76_320,
    death_count: 892,
    injury_count: 31_440,
    malfunction_count: 43_988,
    recall_count: 22,
    recall_rate: 0.29,
    severity_score: 55,
    events_by_month: months12(6_360),
    top_devices: [
      { id: 'triathlon-knee', name: 'Triathlon Total Knee System', count: 22_100 },
    ],
    device_classes: { 'Class I': 3_100, 'Class II': 50_000, 'Class III': 23_220 },
    last_updated: null,
    supply_chain_risk_score: 3.4,
    supply_chain_summary:
      'Stryker operates a largely domestic manufacturing footprint with secondary facilities in Europe. Orthopedic implant supply chains are relatively stable with low single-source exposure. Continuous quality improvement programs maintain supplier reliability.',
    countries: ['USA', 'Germany', 'Ireland'],
    risk_tier: 'LOW',
    recall_risk_score: 0.31,
    specialties: [],
    projected_event_rate_trend: 'DECREASING',
  },
  {
    id: 'becton-dickinson',
    name: 'Becton, Dickinson and Company',
    country: 'USA',
    total_events: 64_091,
    death_count: 411,
    injury_count: 28_500,
    malfunction_count: 35_180,
    recall_count: 18,
    recall_rate: 0.28,
    severity_score: 44,
    events_by_month: months12(5_340),
    top_devices: [
      { id: 'alaris-pump', name: 'Alaris IV Infusion Pump', count: 28_900 },
    ],
    device_classes: { 'Class I': 5_200, 'Class II': 46_000, 'Class III': 12_891 },
    last_updated: null,
    supply_chain_risk_score: 2.9,
    supply_chain_summary:
      'BD has one of the most resilient supply chains in the industry, with manufacturing spread across 40+ countries and robust buffer-stock programs. Consumables are primarily domestically sourced, and electronic component risks are mitigated through pre-positioned inventory.',
    countries: ['USA', 'Mexico', 'Brazil', 'Singapore', 'France'],
    risk_tier: 'LOW',
    recall_risk_score: 0.28,
    specialties: [],
    projected_event_rate_trend: 'DECREASING',
  },
]

export const MOCK_DEVICES: Device[] = [
  {
    id: 'insulin-pump-670g',
    manufacturer_id: 'medtronic',
    manufacturer_name: 'Medtronic, Inc.',
    brand_name: 'MiniMed 670G',
    generic_name: 'Insulin Pump',
    product_code: 'KZH',
    device_class: 'Class III',
    medical_specialty: 'Endocrinology',
    total_events: 31_200,
    death_count: 48,
    injury_count: 12_400,
    malfunction_count: 18_752,
    recall_count: 8,
    recall_rate: 0.26,
    severity_score: 62,
    events_by_month: months12(2_600),
    top_problems: [
      'Inaccurate glucose reading',
      'Reservoir leak',
      'Software malfunction',
      'Alarm failure',
      'Occlusion',
    ],
    last_updated: null,
    recall_risk_score: 0.68,
    risk_tier: 'HIGH',
    projected_event_rate_trend: 'INCREASING',
  },
  {
    id: 'freestyle-libre',
    manufacturer_id: 'abbott',
    manufacturer_name: 'Abbott Laboratories',
    brand_name: 'FreeStyle Libre 3',
    generic_name: 'Continuous Glucose Monitor',
    product_code: 'PFS',
    device_class: 'Class II',
    medical_specialty: 'Endocrinology',
    total_events: 42_100,
    death_count: 12,
    injury_count: 15_600,
    malfunction_count: 26_488,
    recall_count: 3,
    recall_rate: 0.07,
    severity_score: 38,
    events_by_month: months12(3_508),
    top_problems: [
      'Inaccurate reading',
      'Adhesion failure',
      'Sensor error',
      'App connectivity issue',
      'Skin irritation',
    ],
    last_updated: null,
    recall_risk_score: 0.22,
    risk_tier: 'LOW',
    projected_event_rate_trend: 'STABLE',
  },
  {
    id: 'watchman-flx',
    manufacturer_id: 'boston-scientific',
    manufacturer_name: 'Boston Scientific Corporation',
    brand_name: 'WATCHMAN FLX',
    generic_name: 'Left Atrial Appendage Closure Device',
    product_code: 'QFP',
    device_class: 'Class III',
    medical_specialty: 'Cardiology',
    total_events: 18_200,
    death_count: 420,
    injury_count: 9_800,
    malfunction_count: 7_980,
    recall_count: 5,
    recall_rate: 0.27,
    severity_score: 81,
    events_by_month: months12(1_516),
    top_problems: [
      'Device embolization',
      'Pericardial effusion',
      'Stroke post-implant',
      'Incomplete seal',
      'Delivery system failure',
    ],
    last_updated: null,
    recall_risk_score: 0.77,
    risk_tier: 'HIGH',
    projected_event_rate_trend: 'INCREASING',
  },
  {
    id: 'alaris-pump',
    manufacturer_id: 'becton-dickinson',
    manufacturer_name: 'Becton, Dickinson and Company',
    brand_name: 'Alaris PC Unit',
    generic_name: 'IV Infusion Pump',
    product_code: 'FRN',
    device_class: 'Class II',
    medical_specialty: 'Anesthesiology',
    total_events: 28_900,
    death_count: 201,
    injury_count: 11_200,
    malfunction_count: 17_499,
    recall_count: 6,
    recall_rate: 0.21,
    severity_score: 57,
    events_by_month: months12(2_408),
    top_problems: [
      'Over-infusion',
      'Air-in-line alarm failure',
      'Software error',
      'Battery failure',
      'Keypad malfunction',
    ],
    last_updated: null,
    recall_risk_score: 0.45,
    risk_tier: 'MEDIUM',
    projected_event_rate_trend: 'STABLE',
  },
  {
    id: 'triathlon-knee',
    manufacturer_id: 'stryker',
    manufacturer_name: 'Stryker Corporation',
    brand_name: 'Triathlon Total Knee System',
    generic_name: 'Total Knee Replacement',
    product_code: 'KYF',
    device_class: 'Class II',
    medical_specialty: 'Orthopedics',
    total_events: 22_100,
    death_count: 88,
    injury_count: 9_900,
    malfunction_count: 12_112,
    recall_count: 4,
    recall_rate: 0.18,
    severity_score: 49,
    events_by_month: months12(1_841),
    top_problems: [
      'Component loosening',
      'Polyethylene wear',
      'Fracture',
      'Malalignment',
      'Infection',
    ],
    last_updated: null,
    recall_risk_score: 0.29,
    risk_tier: 'LOW',
    projected_event_rate_trend: 'DECREASING',
  },
]
